#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Regression generator + runner for the MMU UVM testbench.

Single entry point for two jobs:

  1. GENERATE a regression.yaml from a (simulator x test x seed) matrix.
  2. RUN a regression.yaml — a target DAG executed locally (thread pool) or
     through an arbitrary job-submit wrapper (LSF/SLURM/...).

No dependency on any proprietary tooling; Python 3.6+, stdlib only (PyYAML is
used when installed, otherwise a built-in minimal parser handles the yaml we
generate).

Usage:
    runreg.py                            # generate only -> regress/regression.yaml
    runreg.py --random -n 10             # 10 random seeds per test
    runreg.py --run -j 8                 # generate, then run locally
    runreg.py --random -n 10 --run -j 8 --submit 'bsub -q myqueue -I'
    runreg.py regress/nightly.yaml -j 8  # run an EXISTING yaml
    runreg.py --clean --keep 2           # remove old regression output

regression.yaml schema (subset):

    config:                 # optional, informational
      project: mmu
      owners: alice

    build_mmu_tb_vcs:
      command: "make -C /path compile SIM=vcs"

    test_vcs_mmu_ifu_test_s1:
      command: "make -C /path run-only SIM=vcs TEST=mmu_ifu_test PT_SEED=1"
      deps: [build_mmu_tb_vcs]
      ignore_failed_deps: false   # optional

Targets run once all their deps have succeeded. A target whose dep failed is
SKIPPED (unless ignore_failed_deps: true). Exit status is non-zero if any
target failed or was skipped.
"""

import argparse
import concurrent.futures as cf
import fnmatch
import os
import random
import re
import shlex
import subprocess
import sys
import threading
import time
from datetime import datetime
from pathlib import Path

# Upper bound for generated seeds. VCS +ntb_random_seed and the PT generator
# both accept a 31-bit positive integer.
SEED_MAX = 2**31 - 1

# repo root = parent of this script's directory (regress/)
ROOT = Path(__file__).resolve().parent.parent

# Per-test extra plusargs. Anything test-specific (fault modes, dynamic PT,
# etc.) goes here; seeds are applied automatically via PT_SEED.
TESTS = {
    "mmu_ifu_test":     "+PT_DYNAMIC",
    "mmu_lsu_test":     "+PT_DYNAMIC",
    "mmu_ifu_lsu_test": "+PT_DYNAMIC",
    "mmu_tlb_inv_test": "+PT_DYNAMIC",
}


# ============================================================== generator side
def yaml_quote(s: str) -> str:
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'


def build_target_name(sim: str) -> str:
    return f"build_mmu_tb_{sim}"


def sim_vars(sim: str) -> str:
    """Extra make variables required by a given simulator backend.

    Verilator needs VERILATOR_UVM=1 to build/run the full UVM testbench
    (default 0 only lints the synthesizable DUT).
    """
    return " VERILATOR_UVM=1" if sim == "verilator" else ""

def pick_seeds(count, seed0, rng):
    """Seed list for one test: random & unique when rng is given, else
    sequential from seed0."""
    if rng is None:
        return [seed0 + i for i in range(count)]
    return sorted(rng.sample(range(1, SEED_MAX), count))


def gen(sims, tests, seeds, seed0, cov_en, root, owners, project,
        rng=None, master_seed=None):
    lines = []
    lines.append("# Auto-generated by regress/runreg.py — do not hand-edit.")
    lines.append("# Regenerate: regress/runreg.py [options]")
    lines.append("#")
    lines.append("# PORTABLE: commands use \"$MMU_TB_ROOT\" instead of a hardcoded path, so")
    lines.append("# this file works in any user's checkout. runreg.py exports MMU_TB_ROOT")
    lines.append("# automatically (the repo containing runreg.py). If you run these commands")
    lines.append("# by hand or through another launcher, set it first:")
    lines.append("#   export MMU_TB_ROOT=/path/to/tt-riscv-mmu-tb")
    if master_seed is not None:
        lines.append(f"# Random seeds generated with --master-seed {master_seed}")
        lines.append(f"# (re-run with the same --master-seed to reproduce this exact seed set)")
    lines.append("")
    lines.append("config:")
    lines.append(f"  project: {project}")
    lines.append(f"  owners: {owners}")
    lines.append("")

    # COV=1 enables functional + code coverage (Makefile: +define+MMU_COVERAGE
    # and -cm ...). Harmless for verilator: the covergroups are compiled out
    # there regardless (mmu_coverage_pkg guards on VERILATOR), so the same flag
    # can be passed to every sim without special-casing.
    cov = " COV=1" if cov_en else ""

    # Build targets (one per sim).
    for sim in sims:
        bname = build_target_name(sim)
        cmd = (f"make -C \"$MMU_TB_ROOT\" compile "
               f"SIM={sim}{sim_vars(sim)}{cov}")
        lines.append(f"{bname}:")
        lines.append(f"  command: {yaml_quote(cmd)}")
        lines.append("")

    # Test targets (test x seed), each depending on its sim build.
    for sim in sims:
        bname = build_target_name(sim)
        for test in tests:
            extra = TESTS.get(test, "")
            for seed in pick_seeds(seeds, seed0, rng):
                tname = f"test_{sim}_{test}_s{seed}"
                args = f"+PT_SEED={seed}" + (f" {extra}" if extra else "")
                # run-only (not run): reuse the simv built by the build target;
                # do NOT recompile C++ (ptgen/sysmem) on the LSF exec node.
                cmd = (f"make -C \"$MMU_TB_ROOT\" run-only "
                       f"SIM={sim}{sim_vars(sim)} "
                       f"TEST={test} PT_SEED={seed} "
                       f"ARGS={yaml_quote(args)}{cov}")
                lines.append(f"{tname}:")
                lines.append(f"  command: {yaml_quote(cmd)}")
                lines.append(f"  deps: [{bname}]")
                lines.append("")

    return "\n".join(lines) + "\n"


# ================================================================ engine side
def clean_outputs(root, keep=0, dry_run=False):
    """Remove regression logs (regressions/<stamp>/) and per-test sim run dirs
    (build/<test>_seed<n>/). Keeps the `keep` most recent regression dirs.
    Never touches build/simv, build/lib or other build artefacts."""
    import shutil

    removed = 0
    regr_root = root / "regressions"
    if regr_root.is_dir():
        stamps = sorted([d for d in regr_root.iterdir() if d.is_dir()],
                        key=lambda p: p.stat().st_mtime, reverse=True)
        for d in stamps[keep:]:
            print("  rm -rf {}".format(d))
            if not dry_run:
                shutil.rmtree(d, ignore_errors=True)
            removed += 1

    build = root / "build"
    if build.is_dir():
        for d in sorted(build.glob("*_seed*")):
            if d.is_dir():
                print("  rm -rf {}".format(d))
                if not dry_run:
                    shutil.rmtree(d, ignore_errors=True)
                removed += 1

    if keep and regr_root.is_dir():
        print("  (kept {} most recent regression dir(s))".format(keep))
    print("clean: removed {} director{}{}".format(
        removed, "y" if removed == 1 else "ies",
        " (dry-run)" if dry_run else ""))
    return 0


def failure_signature(path):
    """Return (display_line, grouping_key) describing why a target failed.

    Reads the target log for the first real UVM_ERROR/UVM_FATAL (skipping the
    "UVM_ERROR :  N" summary counters), else falls back to a crash/make error.
    The grouping key is the same text with volatile detail (hex values, decimal
    numbers, timestamps, paths) replaced by placeholders, so the same bug hit at
    different addresses/seeds/times collapses into one signature.
    """
    if not path or not Path(path).is_file():
        return ("(no log)", "no-log")

    line = None
    try:
        for raw in Path(path).read_text(errors="replace").splitlines():
            if re.search(r"UVM_(ERROR|FATAL)\s*:", raw):
                continue                      # summary counter, not an event
            if "UVM_ERROR" in raw or "UVM_FATAL" in raw:
                line = raw.strip()
                break
            if line is None and ("RUN FAIL" in raw or "%Error" in raw):
                line = raw.strip()            # crash / elab error fallback
    except OSError:
        return ("(unreadable log)", "unreadable")

    if line is None:
        return ("(no UVM_ERROR/UVM_FATAL found)", "unknown")

    # Trim the UVM prefix ("UVM_ERROR file(line) @ time: path [ID] ") so the
    # signature leads with the message itself.
    disp = re.sub(r"^UVM_(ERROR|FATAL)\s+\S+\s+@\s+\d+:\s*\S+\s*", "", line)

    key = disp
    key = re.sub(r"0x[0-9a-fA-F]+", "0x<H>", key)
    key = re.sub(r"@\s*\d+", "@<T>", key)
    key = re.sub(r"\b\d+\b", "<N>", key)
    key = re.sub(r"/\S+/", "<PATH>/", key)
    key = re.sub(r"\s+", " ", key).strip()
    return (disp, key)


def read_excluded_hosts(path):
    """Read a host-exclusion file: one host per line, '#' starts a comment."""
    hosts = []
    if not path or not Path(path).is_file():
        return hosts
    for line in Path(path).read_text().splitlines():
        line = line.split("#", 1)[0].strip()
        if line:
            hosts.append(line)
    return hosts


def lsf_exclude_flag(hosts):
    """Build an LSF resource-requirement that excludes the given hosts.

    'bsub -m "all ~host"' is not accepted by all LSF configs, so use the
    portable select[] form:  -R "select[hname!='a' && hname!='b']"
    """
    if not hosts:
        return ""
    expr = " && ".join("hname!='{}'".format(h) for h in hosts)
    return "-R \"select[{}]\"".format(expr)


def load_yaml(path: Path) -> dict:
    """Load the regression yaml. Uses PyYAML when available, else a minimal
    parser covering the subset emitted by runreg.py."""
    text = path.read_text()
    try:
        import yaml  # type: ignore
        return yaml.safe_load(text) or {}
    except ImportError:
        return _mini_yaml(text)


def _mini_yaml(text: str) -> dict:
    """Tiny parser: top-level 'key:' blocks with 2-space indented
    'field: value' entries. Supports inline lists [a, b] and quoted scalars."""
    out = {}
    cur = None
    for raw in text.splitlines():
        line = raw.rstrip()
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        if not line.startswith(" "):                      # top-level target
            key = line.split(":", 1)[0].strip()
            cur = {}
            out[key] = cur
            continue
        if cur is None:
            continue
        m = re.match(r"\s+([A-Za-z_][\w]*)\s*:\s*(.*)$", line)
        if not m:
            continue
        field, val = m.group(1), m.group(2).strip()
        if val.startswith("[") and val.endswith("]"):
            items = [v.strip().strip('"\'') for v in val[1:-1].split(",")]
            cur[field] = [v for v in items if v]
        elif val.lower() in ("true", "false"):
            cur[field] = (val.lower() == "true")
        else:
            if len(val) >= 2 and val[0] == val[-1] and val[0] in "\"'":
                val = val[1:-1]
                val = val.replace('\\"', '"').replace("\\\\", "\\")
            cur[field] = val
    return out


# ------------------------------------------------------------------- the model
class Target:
    __slots__ = ("name", "command", "deps", "ignore_failed_deps",
                 "status", "rc", "log", "seconds")

    def __init__(self, name: str, spec: dict):
        self.name = name
        self.command = spec.get("command", "")
        self.deps = list(spec.get("deps", []) or [])
        self.ignore_failed_deps = bool(spec.get("ignore_failed_deps", False))
        self.status = "pending"      # pending|running|pass|fail|skip
        self.rc = None
        self.log = None
        self.seconds = 0.0


def parse_targets(doc, only, skip):
    targets = {}
    for name, spec in doc.items():
        if name == "config" or not isinstance(spec, dict):
            continue
        if not spec.get("command"):
            continue
        targets[name] = Target(name, spec)

    # --only / --skip filtering (deps of kept targets are always retained)
    if only:
        keep = {n for n in targets if any(fnmatch.fnmatch(n, p) for p in only)}
        frontier = list(keep)
        while frontier:                      # pull in transitive deps
            n = frontier.pop()
            for d in targets.get(n, Target(n, {})).deps:
                if d in targets and d not in keep:
                    keep.add(d)
                    frontier.append(d)
        targets = {n: t for n, t in targets.items() if n in keep}
    if skip:
        drop = {n for n in targets if any(fnmatch.fnmatch(n, p) for p in skip)}
        targets = {n: t for n, t in targets.items() if n not in drop}

    for t in targets.values():               # prune deps outside the set
        t.deps = [d for d in t.deps if d in targets]

    cycle_check(targets)
    return targets


def cycle_check(targets):
    state = {}

    def visit(n, stack):
        if state.get(n) == 2:
            return
        if state.get(n) == 1:
            raise SystemExit(f"ERROR: dependency cycle: {' -> '.join(stack + [n])}")
        state[n] = 1
        for d in targets[n].deps:
            visit(d, stack + [n])
        state[n] = 2

    for n in targets:
        visit(n, [])


# ---------------------------------------------------------------- the executor
class Runner:
    def __init__(self, targets, outdir, submit, dry_run, jobs, verbose,
                 local_globs=None, signatures=False):
        self.targets = targets
        self.outdir = outdir
        self.submit = submit
        self.dry_run = dry_run
        self.jobs = jobs
        self.verbose = verbose
        # --signatures: also group failures by a fuzzed error signature.
        self.signatures = signatures
        # Targets matching these globs always run locally, even when --submit
        # is given (e.g. builds that need toolchain/headers absent on the farm).
        self.local_globs = list(local_globs or [])
        self.lock = threading.Lock()

    def runs_local(self, name):
        return any(fnmatch.fnmatch(name, p) for p in self.local_globs)

    def log(self, msg: str) -> None:
        with self.lock:
            print(msg, flush=True)

    def runnable(self):
        """Targets whose deps are all resolved; mark unrunnable ones skipped."""
        ready = []
        for t in self.targets.values():
            if t.status != "pending":
                continue
            dep_status = [self.targets[d].status for d in t.deps]
            if any(s in ("pending", "running") for s in dep_status):
                continue
            bad = [d for d in t.deps
                   if self.targets[d].status in ("fail", "skip")]
            if bad and not t.ignore_failed_deps:
                t.status = "skip"
                self.log(f"  SKIP  {t.name}  (dep failed: {', '.join(bad)})")
                continue
            ready.append(t)
        return ready

    def execute(self, t: Target) -> Target:
        t.log = self.outdir / f"{t.name}.log"
        local = self.runs_local(t.name)
        cmd = f"{self.submit} {t.command}" if (self.submit and not local) \
              else t.command
        where = "local" if (local or not self.submit) else "farm"
        self.log(f"  RUN   {t.name}  [{where}]")
        if self.verbose:
            self.log(f"        $ {cmd}")
        if self.dry_run:
            t.status, t.rc = "pass", 0
            t.log.write_text(f"[dry-run] {cmd}\n")
            return t
        start = time.time()
        # Generated commands reference "$MMU_TB_ROOT" rather than a hardcoded
        # path so the yaml is portable across checkouts. Export it here (the
        # repo containing this script) unless the caller already set it.
        env = dict(os.environ)
        env.setdefault("MMU_TB_ROOT", str(ROOT))
        with open(t.log, "w") as fh:
            fh.write(f"# target : {t.name}\n# command: {cmd}\n"
                     f"# MMU_TB_ROOT: {env['MMU_TB_ROOT']}\n\n")
            fh.flush()
            t.rc = subprocess.call(cmd, shell=True, stdout=fh,
                                   stderr=subprocess.STDOUT, env=env)
        t.seconds = time.time() - start
        t.status = "pass" if t.rc == 0 else "fail"
        mark = "PASS " if t.rc == 0 else "FAIL "
        self.log(f"  {mark} {t.name}  (rc={t.rc}, {t.seconds:.1f}s)")
        return t

    def run(self) -> int:
        total = len(self.targets)
        self.log(f"Running {total} target(s) with -j{self.jobs}"
                 f"{' [dry-run]' if self.dry_run else ''}\n")
        with cf.ThreadPoolExecutor(max_workers=self.jobs) as pool:
            inflight = {}
            while True:
                for t in self.runnable():
                    # Mark running here (not in the worker) so the next
                    # runnable() pass cannot re-submit the same target.
                    t.status = "running"
                    inflight[pool.submit(self.execute, t)] = t
                if not inflight:
                    break
                done, _ = cf.wait(list(inflight),
                                  return_when=cf.FIRST_COMPLETED)
                for fut in done:
                    inflight.pop(fut)
                    fut.result()
        return self.summary()

    def summary(self) -> int:
        order = ["fail", "skip", "pass"]
        by = {s: [t for t in self.targets.values() if t.status == s]
              for s in order}
        width = max((len(n) for n in self.targets), default=10)
        print("\n" + "=" * (width + 26))
        print("REGRESSION SUMMARY")
        print("=" * (width + 26))
        for t in sorted(self.targets.values(), key=lambda x: x.name):
            rc = "-" if t.rc is None else str(t.rc)
            print(f"  {t.status.upper():5} {t.name:<{width}}  rc={rc:<4} "
                  f"{t.seconds:6.1f}s")
        print("-" * (width + 26))
        print(f"  pass={len(by['pass'])}  fail={len(by['fail'])}  "
              f"skip={len(by['skip'])}  total={len(self.targets)}")
        print(f"  logs: {self.outdir}")
        if by["fail"]:
            print("\n  Failed targets:")
            for t in by["fail"]:
                # One path is enough: the per-target log is a SUPERSET of the
                # simulator's own run.log (both backends replay the full
                # transcript to stdout), so it already has every detail.
                print(f"    {t.name}  ->  {t.log}")

            if self.signatures:
                # Group by fuzzed signature so failures sharing a root cause
                # collapse into one bucket.
                buckets = {}
                for t in by["fail"]:
                    disp, key = failure_signature(t.log)
                    buckets.setdefault(key, [disp, []])[1].append(t.name)
                print(f"\n  Failed signatures ({len(buckets)} distinct):")
                for disp, names in sorted(buckets.values(),
                                          key=lambda v: -len(v[1])):
                    print(f"    [{len(names)}x] {disp}")
                    for n in names:
                        print(f"           {n}")
        print("=" * (width + 26))
        return 1 if (by["fail"] or by["skip"]) else 0



# ==================================================================== main
def main():
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)

    ap.add_argument("yaml", nargs="?",
                    help="run this EXISTING regression yaml (skips generation). "
                         "Omit to generate one from the matrix options below.")

    g = ap.add_argument_group("generation")
    g.add_argument("--sims", nargs="+", default=["vcs", "verilator"],
                   help="simulators to build/run (default: vcs verilator)")
    g.add_argument("--tests", nargs="+", default=list(TESTS.keys()),
                   help="UVM tests to run (default: all in TESTS)")
    g.add_argument("--seeds", "-n", type=int, default=3,
                   help="number of runs (seeds) per test (default: 3)")
    g.add_argument("--seed0", type=int, default=1,
                   help="first seed for sequential mode (default: 1)")
    g.add_argument("--random", action="store_true",
                   help="use random unique seeds instead of sequential")
    g.add_argument("--master-seed", type=int, default=None, metavar="N",
                   help="with --random, seed the seed-generator so the yaml is "
                        "reproducible (recorded in the yaml header)")
    g.add_argument("--cov", action="store_true",
                   help="build and run with COV=1: functional coverage "
                        "(mmu_paging_cg) + VCS code coverage into "
                        "build/cov.vdb. Report afterwards with "
                        "'make cov_report SIM=vcs COV=1'. No effect under "
                        "verilator (covergroups are compiled out there).")
    g.add_argument("--owners", default=os.environ.get("USER", "unknown"),
                   help="regression owner(s)")
    g.add_argument("--project", default="mmu",
                   help="project name recorded in the yaml (default: mmu)")
    g.add_argument("--out", default=str(ROOT / "regress" / "temp.yaml"),
                   help="output yaml path (default: regress/temp.yaml — a "
                        "gitignored scratch file, so the checked-in "
                        "regression.yaml/nightly.yaml are never clobbered by "
                        "accident. Pass --out explicitly to update those.)")
    g.add_argument("--run", action="store_true",
                   help="after generating, immediately run the regression "
                        "(default: generate only)")

    r = ap.add_argument_group("execution")
    r.add_argument("-j", "--jobs", type=int, default=os.cpu_count() or 4,
                   help="max targets to run concurrently")
    r.add_argument("-o", "--outdir",
                   help="log directory (default: regressions/<timestamp>)")
    r.add_argument("--submit", default="",
                   help="prefix each command with a submit wrapper, e.g. "
                        "--submit 'bsub -q myqueue -I'")
    r.add_argument("--local", action="append", metavar="GLOB",
                   help="run targets matching GLOB locally even when --submit "
                        "is given (repeatable). Defaults to 'build_*'; pass "
                        "--local '' to disable.")
    r.add_argument("--exclude-host", action="append", metavar="HOST", default=[],
                   help="exclude an LSF host from dispatch (repeatable)")
    r.add_argument("--exclude-file", metavar="FILE",
                   default=str(Path(__file__).resolve().parent /
                               "excluded_hosts.txt"),
                   help="file of hosts to exclude, one per line ('#' comments). "
                        "Default: regress/excluded_hosts.txt. Pass '' to skip.")
    r.add_argument("--only", action="append", metavar="GLOB",
                   help="only run targets matching GLOB (repeatable)")
    r.add_argument("--skip", action="append", metavar="GLOB",
                   help="skip targets matching GLOB (repeatable)")
    r.add_argument("-v", "--verbose", action="store_true",
                   help="echo each command")
    r.add_argument("--signatures", "--sig", action="store_true",
                   help="in the summary, also print a 'Failed signatures' "
                        "section: the actual UVM_ERROR/UVM_FATAL text of each "
                        "failure, grouped so failures sharing a root cause "
                        "collapse into one bucket")

    c = ap.add_argument_group("housekeeping")
    c.add_argument("--clean", action="store_true",
                   help="delete regression logs (regressions/) and per-test sim "
                        "run dirs (build/*_seed*), then exit")
    c.add_argument("--keep", type=int, default=0, metavar="N",
                   help="with --clean, keep the N most recent regression dirs")
    c.add_argument("--dry-run", action="store_true",
                   help="resolve and print the DAG without executing (with "
                        "--clean, list what would be removed)")

    args = ap.parse_args()

    # ---- housekeeping only -------------------------------------------------
    if args.clean:
        print("cleaning regression output under {}".format(ROOT))
        return clean_outputs(ROOT, keep=max(0, args.keep),
                             dry_run=args.dry_run)

    # ---- pick the yaml: existing, or generate one --------------------------
    if args.yaml:
        ypath = Path(args.yaml)
        if not ypath.is_file():
            print("ERROR: yaml not found: {}".format(ypath), file=sys.stderr)
            return 2
        print("regression : {} (existing)".format(ypath))
    else:
        rng = None
        master_seed = None
        if args.random:
            master_seed = (args.master_seed if args.master_seed is not None
                           else random.randrange(1, SEED_MAX))
            rng = random.Random(master_seed)

        text = gen(args.sims, args.tests, args.seeds, args.seed0,
                   args.cov, ROOT, args.owners, args.project,
                   rng=rng, master_seed=master_seed)
        ypath = Path(args.out)
        ypath.parent.mkdir(parents=True, exist_ok=True)
        ypath.write_text(text)

        ntests = len(args.sims) * len(args.tests) * args.seeds
        mode = ("random seeds (--master-seed {})".format(master_seed) if rng
                else "sequential seeds from {}".format(args.seed0))
        print("Wrote {} : {} build(s) + {} test target(s)".format(
            ypath, len(args.sims), ntests))
        print("  {} seed(s)/test, {}".format(args.seeds, mode))

        if not args.run:
            print("  run it with: regress/runreg.py {}".format(ypath))
            return 0

    # ---- run it -----------------------------------------------------------
    doc = load_yaml(ypath)
    targets = parse_targets(doc, args.only, args.skip)
    if not targets:
        print("ERROR: no runnable targets found", file=sys.stderr)
        return 2

    # Builds stay local by default (toolchain/headers may be missing on the
    # farm); tests are farmed out. --local '' disables.
    if args.local is None:
        local_globs = ["build_*"] if args.submit else []
    else:
        local_globs = [g for g in args.local if g]

    # Host exclusion -> LSF select[] expression appended to the submit wrapper.
    submit = args.submit
    excluded = sorted(set(list(args.exclude_host) +
                          read_excluded_hosts(args.exclude_file)))
    if submit and excluded:
        submit = "{} {}".format(submit, lsf_exclude_flag(excluded))

    stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    outdir = Path(args.outdir) if args.outdir else Path("regressions") / stamp
    outdir.mkdir(parents=True, exist_ok=True)

    cfg = doc.get("config") or {}
    if cfg:
        print("config     : " + "  ".join("{}={}".format(k, v)
                                          for k, v in cfg.items()))
    if submit:
        print("submit     : {}".format(submit))
        print("local-only : {}".format(", ".join(local_globs) or "(none)"))
        print("excluded   : {}".format(", ".join(excluded) or "(none)"))
    print("logs       : {}\n".format(outdir))

    return Runner(targets, outdir, submit, args.dry_run,
                  max(1, args.jobs), args.verbose, local_globs,
                  signatures=args.signatures).run()


if __name__ == "__main__":
    sys.exit(main())
